terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
bash: line 8: 16898 Aborted                 (core dumped) ./a.out
