+ g++-4.8 -std=c++11 -O2 -Wall -pedantic -pthread main.cpp
+ ./a.out
terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device::random_device(const std::string&)
/tmp/1376219325-1125914211/cmd.sh: line 8: 11663 Aborted                 (core dumped) ./a.out
