terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
bash: line 7: 22993 Aborted                 (core dumped) ./a.out
